### 
GET http://localhost:5000/users

###
GET http://localhost:5000/excercises

### 
POST http://localhost:5000/users/add
Content-Type: application/json

{
    "username" : "devansh srivastava"
}

###
POST http://localhost:5000/excercises/add
Content-Type: application/json

{
    "username" : "John Doe",
    "description" : "sleep",
    "duration" : 8,
    "date" : "2021-11-24T16:44:09.294Z"
}

###
GET http://localhost:5000/excercises/619e6d01f4b80e7d51271051

###
DELETE http://localhost:5000/excercises/619e6d01f4b80e7d51271051

###
POST http://localhost:5000/excercises/update/619e6d01f4b80e7d51271051
Content-Type: application/json

{
    "username" : "Harsh Anand updated",
    "description": "Run Run Run",
    "duration": 30,
    "date": "2021-11-24T16:44:09.294Z"
}